propiedad/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
     path("web/",include('web.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from .views import index,registro,perfil,modificar_perfil,obtener_comunas,formulario_view,listar_propiedades_usuario
from .views import agregar_propiedad,borrar_propiedad,listar_propiedades,detalle_propiedad, PropiedadUpdateView

urlpatterns = [
   
    path("propiedades/", index, name= 'index'),
    path('registro/', registro, name='registro'),
    path('perfil/', perfil, name='perfil'),
    path('perfil/modificar/', modificar_perfil, name='modificar_perfil'),
    path('formulario/', formulario_view, name='formulario'),
    path('obtener_comunas/', obtener_comunas, name='obtener_comunas'),
    
    path('propiedades/agregar/', agregar_propiedad, name='agregar_propiedad'),
    path('propiedades/<int:pk>/editar/', PropiedadUpdateView.as_view(), name='editar_propiedad'),
    path('propiedades/<int:propiedad_id>/borrar/', borrar_propiedad, name='borrar_propiedad'),
    path('propiedades/usuario/', listar_propiedades_usuario, name='listar'),
    path('propiedades/<int:propiedad_id>/', detalle_propiedad, name='detalle_propiedad'),
    path("", listar_propiedades, name='listar_propiedades'),
    
    
    path('accounts/', include('django.contrib.auth.urls')),
   
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    rut = models.CharField(max_length=12, unique=True)
    telefono_personal = models.CharField(max_length=15)
    tipo_usuario_choices = [
        ('arrendatario', 'Arrendatario'),
        ('arrendador', 'Arrendador'),
    ]
    tipo_usuario = models.CharField(max_length=12, choices=tipo_usuario_choices, default='arrendatario')
    direccion = models.ForeignKey('Direccion',on_delete=models.CASCADE,  null=True)
    
     # Define related_name único para los campos ManyToManyField
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_users',  # Ejemplo de related_name único
        blank=True,
        verbose_name='groups',
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.'
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_users',  # Ejemplo de related_name único
        blank=True,
        verbose_name='user permissions',
        help_text='Specific permissions for this user.'
    )

    def __str__(self):
        return f"{self.username} {self.last_name}"
    
class TipoPropiedad(models.Model):
    nombre_tipo = models.CharField( max_length=50)
    def __str__(self):
        return self.nombre_tipo
        
class Propiedad(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    m2_construidos = models.DecimalField(max_digits=10, decimal_places=2)
    m2_terreno = models.DecimalField(max_digits=10, decimal_places=2)
    num_estacionamientos = models.IntegerField()
    num_habitaciones = models.IntegerField()
    num_banos = models.IntegerField()
    direccion = models.ForeignKey('Direccion', on_delete=models.SET_NULL, null=True)
    tipo_propiedad = models.ForeignKey(TipoPropiedad, on_delete=models.CASCADE, related_name='propiedad')
    precio_mensual = models.DecimalField(max_digits=10, decimal_places=2)
    arrendador = models.ForeignKey(Usuario, related_name='propiedades_arrendadas', on_delete=models.CASCADE)
    arrendatario = models.ForeignKey(Usuario, related_name='propiedades_arrendadas_a_mi', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.nombre}y el tipo {self.tipo_propiedad}"
    
    
class ImagenPropiedad(models.Model):
    propiedad = models.ForeignKey(Propiedad, related_name='imagenes', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='propiedades/')
    descripcion = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"Imagen de '{self.propiedad.nombre}'"    

class SolicitudArriendo(models.Model):
    ESTADO_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('aprobada', 'Aprobada'),
        ('rechazada', 'Rechazada'),
    ]

    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha_solicitud = models.DateField(auto_now_add=True)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='pendiente')

    def __str__(self):
        return f"Solicitud de arriendo de {self.usuario} para {self.propiedad}"
    
class Region(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    # Otros campos relevantes para la región
    def __str__(self):
        return self.nombre
    
class Comuna(models.Model):
    nombre = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.nombre}"   
     
class Direccion(models.Model):
    calle = models.CharField(max_length=255)
    numero = models.CharField(max_length=10)
    punto_referencia = models.CharField(max_length=255, blank=True, null=True)
    comuna = models.ForeignKey('Comuna', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        if self.punto_referencia:
            return f"{self.calle} {self.numero}, {self.punto_referencia}, {self.comuna}"
        else:
            return f"{self.calle} {self.numero}, {self.comuna}"

web/forms.py
from django import forms
from .models import Usuario, Region, Comuna, Direccion,Propiedad,ImagenPropiedad,TipoPropiedad
from django.contrib.auth.forms import AuthenticationForm
from django.forms import formset_factory
from django.forms import inlineformset_factory

class UsuarioUpdateForm(forms.ModelForm):
    direccion_calle = forms.CharField(max_length=255)
    direccion_numero = forms.CharField(max_length=10)
    direccion_punto_referencia = forms.CharField(max_length=255, required=False)
    region = forms.ModelChoiceField(queryset=Region.objects.all(), empty_label="Seleccionar región")
    comuna = forms.ModelChoiceField(queryset=Comuna.objects.none(), empty_label="Seleccionar comuna")

    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'rut', 'email', 'telefono_personal', 'tipo_usuario', 'region', 'comuna']
        labels = {
            'first_name':'Nombre',
            'last_name': 'Apellido',
            'username': 'Nombre de usuario',
            'email': 'Correo electrónico',
            'telefono_personal': 'Teléfono',
            'region': 'Región',
            'comuna': 'Comuna',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        if self.instance:
            # Verificar si la instancia tiene una región definida
            if hasattr(self.instance, 'direccion') and self.instance.direccion and self.instance.direccion.comuna:
                self.fields['direccion_calle'].initial = self.instance.direccion.calle
                self.fields['direccion_numero'].initial = self.instance.direccion.numero
                self.fields['direccion_punto_referencia'].initial = self.instance.direccion.punto_referencia
                self.fields['region'].initial = self.instance.direccion.comuna.region
                self.fields['comuna'].queryset = Comuna.objects.filter(region=self.instance.direccion.comuna.region).order_by('nombre')
            else:
                # Si no hay una región definida para la instancia, dejar el queryset vacío
                self.fields['comuna'].queryset = Comuna.objects.none()
        else:
            # Cuando se está creando un nuevo usuario, se deja el queryset de comuna vacío inicialmente
            self.fields['comuna'].queryset = Comuna.objects.none()

    def save(self, commit=True):
        usuario = super().save(commit=False)
        direccion_calle = self.cleaned_data['direccion_calle']
        direccion_numero = self.cleaned_data['direccion_numero']
        direccion_punto_referencia = self.cleaned_data['direccion_punto_referencia']
        region = self.cleaned_data['region']
        comuna = self.cleaned_data['comuna']

        # Buscar o crear la dirección
        direccion, created = Direccion.objects.get_or_create(
            calle=direccion_calle,
            numero=direccion_numero,
            punto_referencia=direccion_punto_referencia,
            comuna=comuna
        )

        usuario.direccion = direccion

        if commit:
            usuario.save()

        return usuario

class UsuarioForm(forms.ModelForm):
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput)
    region = forms.ModelChoiceField(queryset=Region.objects.all(), empty_label="Seleccionar región")
    comuna = forms.ModelChoiceField(queryset=Comuna.objects.none(), empty_label="Seleccionar comuna")
    
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name','username', 'rut', 'email', 'telefono_personal', 'region', 'comuna']
        labels = {
            'first_name':'Nombre',
            'last_name': 'Apellido',
            'username': 'Nombre de usuario',
            'email': 'Correo electrónico',
            'telefono_personal': 'Teléfono',
            'region': 'Región',
            'comuna': 'Comuna',
        }
        error_messages = {
            'username': {
                'unique': 'Ya existe un usuario con ese nombre de usuario. Por favor, elige otro.',
            }
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Cargar las regiones disponibles en el formulario
        self.fields['region'].queryset = Region.objects.all()

        # Si hay datos posteados (POST request), filtrar las comunas basadas en la región seleccionada
        if 'region' in self.data:
            try:
                region_id = int(self.data.get('region'))
                self.fields['comuna'].queryset = Comuna.objects.filter(region_id=region_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # Si hay algún error al intentar obtener el ID de la región, no se filtra nada
        
        # Si ya existe una instancia de usuario (estamos en una actualización), cargar las opciones seleccionadas
        elif self.instance.pk and self.instance.direccion and self.instance.direccion.comuna:
            self.fields['region'].initial = self.instance.direccion.comuna.region
            self.fields['comuna'].queryset = Comuna.objects.filter(region=self.instance.direccion.comuna.region).order_by('nombre')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()

            # Asignar la dirección al usuario si existe
            if 'region' in self.cleaned_data and 'comuna' in self.cleaned_data:
                region_id = self.cleaned_data['region'].id
                comuna_id = self.cleaned_data['comuna'].id
                direccion, created = Direccion.objects.get_or_create(
                    comuna_id=comuna_id,
                    defaults={
                        'calle': 'Sin especificar',
                        'numero': '10',
                        'punto_referencia': 'Sin especificar'
                    }
                )
                user.direccion = direccion
                user.save()

        return user


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Usuario'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'})
    )



class ImagenForm(forms.ModelForm):
    class Meta:
        model = ImagenPropiedad
        fields = ['imagen', 'descripcion']
        
        
        
        # Define el formset fuera del formulario
ImagenFormSet = formset_factory(ImagenForm, extra=5)  # Permitir hasta 5 imágenes

class PropiedadForm(forms.ModelForm):
    # Campos para la dirección
    region = forms.ModelChoiceField(queryset=Region.objects.all(), empty_label="Seleccionar región")
    comuna = forms.ModelChoiceField(queryset=Comuna.objects.none(), empty_label="Seleccionar comuna")
    direccion_calle = forms.CharField(max_length=255)
    direccion_numero = forms.CharField(max_length=10)
    direccion_punto_referencia = forms.CharField(max_length=255, required=False)
    imagen_formset = ImagenFormSet()  # Instanciamos el formset aquí
    
    class Meta:
        model = Propiedad
        fields = ['nombre', 'descripcion', 'm2_construidos', 'm2_terreno', 'num_estacionamientos', 
                  'num_habitaciones', 'num_banos', 'tipo_propiedad', 'precio_mensual', 'region', 'comuna']
        labels = {
            'nombre': 'Nombre',
            'descripcion': 'Descripción',
            'm2_construidos': 'Metros Construidos',
            'm2_terreno': 'Metros de Terreno',
            'num_estacionamientos': 'Número de Estacionamientos',
            'num_habitaciones': 'Número de Habitaciones',
            'num_banos': 'Número de Baños',
            'tipo_propiedad': 'Tipo de Propiedad',
            'precio_mensual': 'Precio Mensual',
            'region': 'Región',
            'comuna': 'Comuna',
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.user = user  # Guardamos el usuario

        # Filtrar las comunas basadas en la región seleccionada si hay datos en la solicitud POST
        if 'region' in self.data:
            try:
                region_id = int(self.data.get('region'))
                self.fields['comuna'].queryset = Comuna.objects.filter(region_id=region_id).order_by('nombre')
            except (ValueError, TypeError):
                self.fields['comuna'].queryset = Comuna.objects.none()
        elif self.instance and self.instance.pk and self.instance.direccion and self.instance.direccion.comuna:
            direccion = self.instance.direccion
            self.fields['region'].initial = direccion.comuna.region
            self.fields['comuna'].queryset = Comuna.objects.filter(region=direccion.comuna.region).order_by('nombre')
            self.fields['comuna'].initial = direccion.comuna
            self.fields['direccion_calle'].initial = direccion.calle
            self.fields['direccion_numero'].initial = direccion.numero
            self.fields['direccion_punto_referencia'].initial = direccion.punto_referencia

    def save(self, commit=True):
        propiedad = super().save(commit=False)

        if self.user:
            propiedad.arrendador = self.user

        if commit:
            propiedad.save()

            # Actualizar o crear la dirección
            direccion, created = Direccion.objects.update_or_create(
                comuna=self.cleaned_data['comuna'],
                calle=self.cleaned_data['direccion_calle'],

web/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <title>
        {% block title %} {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<header>
    
    <!-- Incluir aquí la navegación común a todas las páginas -->
 {% include 'partes/navbar.html' %}
</header>
<body>
    <h1 class="text-center">Arriendo de Inmuebles</h1>
    
    <div class="container">
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <!-- Contenido principal -->
        {% block content %}
        {% endblock %}
    </div>

    {% include 'partes/footer.html' %}
    <!-- Incluir Bootstrap JS desde un CDN -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <!-- Incluir scripts locales si es necesario -->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

web/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
     <!-- Script JavaScript para manejar Ajax -->
     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <form id="formulario-direccion">
        <!-- Campo para seleccionar la región -->
        <select id="id_region">
            <option value="">Selecciona una región</option>
            {% for region in regions %}
                <option value="{{ region.id }}">{{ region.nombre }}</option>
            {% endfor %}
        </select>
    
        <!-- Campo para mostrar las comunas -->
        <select id="id_comuna" name="comuna">
            <option value="">Selecciona una comuna</option>
        </select>
    
        <!-- Otros campos del formulario de dirección -->
        <!-- ... -->
    
        <!-- Botón de enviar -->
        <button type="submit">Guardar dirección</button>
    </form>
    
    <script>
    $(document).ready(function() {
        $('#id_region').change(function() {
            var regionId = $(this).val();
            if (regionId) {
                $.ajax({
                    url: '{% url "obtener_comunas" %}',
                    data: {
                        'region_id': regionId
                    },
                    dataType: 'json',
                    success: function(data) {
                        $('#id_comuna').empty();
                        $.each(data, function(index, comuna) {
                            $('#id_comuna').append('<option value="' + comuna.id + '">' + comuna.nombre + '</option>');
                        });
                    }
                });
            } else {
                $('#id_comuna').empty();
            }
        });
    });
    </script>
</body>
</html>

web/templates/modificar_perfil.html
{% extends 'base.html' %}

{% block title %}
Actualizar Usuario
{% endblock %}

{% block content %}

<div class="container">
    <div class="form-container">
        <h2>Actualizar Usuario</h2>

        <form method="post" id="formulario-usuario">
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div>
                {{ form.first_name.label_tag }}
                {{ form.first_name  }}
                {{ form.first_name.errors }}
            </div>

            <div>
                {{ form.last_name.label_tag }}
                {{ form.last_name  }}
                {{ form.last_name.errors }}
            </div>

            <div>
                {{ form.rut.label_tag }}
                {{ form.rut }}
                {{ form.rut.errors }}
            </div>

            <div>
                {{ form.email.label_tag }}
                {{ form.email  }}
                {{ form.email.errors }}
            </div>

            <div>
                {{ form.telefono_personal.label_tag }}
                {{ form.telefono_personal  }}
                {{ form.telefono_personal.errors }}
            </div>

            <div>
                {{ form.tipo_usuario.label_tag }}
                {{ form.tipo_usuario  }}
                {{ form.tipo_usuario.errors }}
            </div>

            <div>
                {{ form.region.label_tag }}
                {{ form.region }}
                {{ form.region.errors }}
            </div>

            <div>
                {{ form.comuna.label_tag }}
                {{ form.comuna }}
                {{ form.comuna.errors }}
            </div>

            <div>
                {{ form.direccion_calle.label_tag }}
                {{ form.direccion_calle  }}
                {{ form.direccion_calle.errors }}
            </div>

            <div>
                {{ form.direccion_numero.label_tag }}
                {{ form.direccion_numero }}
                {{ form.direccion_numero.errors }}
            </div>

            <div>
                {{ form.direccion_punto_referencia.label_tag }}
                {{ form.direccion_punto_referencia  }}
                {{ form.direccion_punto_referencia.errors }}
            </div>

            <button type="submit">Guardar Usuario</button>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

 <script>
    $(document).ready(function () {
        $('#id_region').change(function () {
            var regionId = $(this).val();
            if (regionId) {
                $.ajax({
                    url: '{% url "obtener_comunas" %}',
                    data: {
                        'region_id': regionId
                    },
                    dataType: 'json',
                    success: function (data) {
                        $('#id_comuna').empty();
                        $.each(data, function (index, comuna) {
                            $('#id_comuna').append('<option value="' + comuna.id + '">' + comuna.nombre + '</option>');
                        });
                    }
                });
            } else {
                $('#id_comuna').empty();
            }
        });

        // Cargar las comunas al cargar la página si la región ya está seleccionada
        var regionId = $('#id_region').val();
        if (regionId) {
            $.ajax({
                url: '{% url "obtener_comunas" %}',
                data: {
                    'region_id': regionId
                },
                dataType: 'json',
                success: function (data) {
                    $('#id_comuna').empty();
                    $.each(data, function (index, comuna) {
                        $('#id_comuna').append('<option value="' + comuna.id + '">' + comuna.nombre + '</option>');
                    });
                }
            });
        }
    });
</script> 

{% endblock %}

web/templates/perfil.html
{% extends 'base.html' %}

{% block title %}
Perfil de usuario
{% endblock %}

{% block content %}
<!-- <style>
   
    }
</style> -->

<div class="profile-container">
    <h2>Perfil de {{ usuario.username }}</h2>
    <p>Nombre: {{ usuario.first_name|title }} {{ usuario.last_name|title  }}</p>
    <p>Email: {{ usuario.email|title  }}</p>
    <p>RUT: {{ usuario.rut|title  }}</p>
    <p>Teléfono personal: {{ usuario.telefono_personal }}</p>
    <p>Tipo de usuario: {{ usuario.get_tipo_usuario_display|title  }}</p>

    <!-- Mostrar la dirección del usuario -->
    {% if usuario.direccion %}
        <h3>Dirección</h3>
        <p>Calle: {{ usuario.direccion.calle|title  }}</p>
        <p>Número: {{ usuario.direccion.numero|title  }}</p>
        <p>Punto de referencia: {{ usuario.direccion.punto_referencia|title  }}</p>
        <p>Comuna: {{ usuario.direccion.comuna.nombre|title  }}</p>
    {% else %}
        <p>Aún no se ha registrado una dirección.</p>
    {% endif %}
</div>
{% endblock %}

web/templates/registrar.html
{% extends 'base.html' %}

{% block title %}
Formulario de Usuario
{% endblock %}

{% block content %}

<!-- Estilos CSS -->
<!-- <style>
    /* Estilos para centrar el formulario */
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh; /* Ajusta la altura según tu necesidad */
    }

    .form-container {
        width: 400px; /* Ancho del formulario */
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 8px;
        background-color: #f9f9f9;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    /* Estilos opcionales para los campos */
    label {
        display: block;
        margin-bottom: 5px;
    }

    .error {
        color: red;
    }

    input[type="text"],
    input[type="email"],
    input[type="tel"],
    input[type="password"],
    select {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        float: right;
    }

    button:hover {
        background-color: #45a049;
    }
</style> -->
</head>

<body>

<div class="container">
    <div class="form-container">
        <h2>Registro de Usuario</h2>

        <form method="post" id="formulario-usuario">
            {% csrf_token %}

            {{ form.non_field_errors }}
        
            <div>
                {{ form.username.label_tag }}
                {{ form.username }}
                {{ form.username.errors }}
            </div>
            <div>
                {{ form.first_name.label_tag }}
                {{ form.first_name }}
                {{ form.first_name.errors }}
            </div>
            <div>
                {{ form.last_name.label_tag }}
                {{ form.last_name }}
                {{ form.last_name.errors }}
            </div>
           

            <div>
                {{ form.rut.label_tag }}
                {{ form.rut }}
                {{ form.rut.errors }}
            </div>

            <div>
                {{ form.email.label_tag }}
                {{ form.email }}
                {{ form.email.errors }}
            </div>

            <div>
                {{ form.telefono_personal.label_tag }}
                {{ form.telefono_personal }}
                {{ form.telefono_personal.errors }}
            </div>

            <div>
                {{ form.region.label_tag }}
                {{ form.region }}
                {{ form.region.errors }}
            </div>

            <div>
                {{ form.comuna.label_tag }}
                {{ form.comuna }}
                {{ form.comuna.errors }}
            </div>

            <div>
                {{ form.calle.label_tag }}
                {{ form.calle }}
                {{ form.calle.errors }}
            </div>
            
            <div>
                {{ form.numero.label_tag }}
                {{ form.numero }}
                {{ form.numero.errors }}
            </div>
            
            <div>
                {{ form.punto_referencia.label_tag }}
                {{ form.punto_referencia }}
                {{ form.punto_referencia.errors }}
            </div>

            <div>
                {{ form.password1.label_tag }}
                {{ form.password1 }}
                {{ form.password1.errors }}
            </div>

            <div>
                {{ form.password2.label_tag }}
                {{ form.password2 }}
                {{ form.password2.errors }}
            </div>

            <button type="submit">Guardar Usuario</button>
        </form>
    </div>
</div>

 <!-- Script JavaScript para manejar la carga dinámica de comunas -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
 
<script>
    $(document).ready(function () {
        $('#id_region').change(function () {
            var regionId = $(this).val();
            if (regionId) {
                $.ajax({
                    url: '{% url "obtener_comunas" %}',
                    data: {
                        'region_id': regionId
                    },
                    dataType: 'json',
                    success: function (data) {
                        $('#id_comuna').empty();
                        $.each(data, function (index, comuna) {
                            $('#id_comuna').append('<option value="' + comuna.id + '">' + comuna.nombre + '</option>');
                        });
                    }
                });
            } else {
                $('#id_comuna').empty();
            }
        });
    });
</script>
 
{% endblock %}